use_frameworks!

platform :ios, '10.0'

target 'PodTestProject_Example' do
  pod 'PodTestProject', :path => '../'

  target 'PodTestProject_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
    pod 'AFNetworking', '~> 2.3'
  end
end
